language: java

services:
  - docker

env:
  jobs:
    - GALAXY_VERSION=18.09
    - GALAXY_VERSION=19.01
    - GALAXY_VERSION=19.05.1
    

before_install:
  - docker pull bgruening/galaxy-stable:${GALAXY_VERSION}
  - docker run -d -p 80:80 --name galaxy bgruening/galaxy-stable:${GALAXY_VERSION}

script:
  - mvn clean test
